# Generated by Django 4.0.4 on 2022-05-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_full_name_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
